### ISSUE TITLE
Multiple accounts configuration

### ISSUE THREAD

**Issue by hiol83** [Barma-lej/halandroid#25] opened 2021-07-12 11:32 UTC
Hi to everybody,
so this is not an issue but only a question.
How is it possible to configure multiple accounts?

**Comment by Barma-lej** [comment] 2021-07-12 11:52
Duplicate of #21

**Comment by Barma-lej** [comment] 2021-07-12 12:04
[See here](https://github.com/MTrab/landroid_cloud#example-entry-for-configurationyaml) then here #21

**Closed as completed** 2021-10-31 15:36 UTC
