### ISSUE TITLE
Sensor causes warning

### ISSUE THREAD

**Issue by yolani** [Barma-lej/halandroid#36] opened 2021-12-15 14:31 UTC
The definition of your template sensors create a warning in the logs since the last home assistant update:

Entity sensor.landroid_rasi_battery (<class 'custom_components.landroid_cloud.sensor.LandroidSensor'>) implements device_state_attributes. Please report it to the custom component author.

Honestly I don't fully understand it, adding attributes to a template sensor is still allowed according to the documentation.

Maybe you would want to look into that, could stop working at some point.

**Comment by Barma-lej** [comment] 2021-12-15 21:34
Duplicate of https://github.com/MTrab/landroid_cloud/issues/87

**Closed as completed by Barma-lej** 2021-12-15 21:34 UTC
